### ISSUE TITLE
How can i send message to another phone number?

### ISSUE THREAD

**Issue by af913337456** [mautrix/gmessages#12]
I checked the code and couldn't find the function to send messages to a certain phone number.

**Comment by tulir** [comment]
`pm <number>`

**Comment by af913337456** [comment]
@tulir thanks to reply.

i see this just open a chat for phone number, but can't send message in one request.

does it means the follow steps:

1. create a chat in one request;
2. send message to this chat;


so i have finish the message sending in two request.
