### ISSUE TITLE
It seem can't send RCS message

### ISSUE THREAD

**Issue by af913337456** [mautrix/gmessages#14]
i use the sendMessage function to send RCS message, which my phone number and the targer both support RCS model and opened. but still get SMS msg.

**Comment by af913337456** [comment]
@hifi @tulir @Fizzadar thanks

**Comment by tulir** [comment]
The method for sending messages is decided by the phone. For dual sim, need to make sure to use the correct `SIMPayload` and `ParticipantID`, but for single sim there's only one option and the sim payload doesn't matter. Using libgm directly is not really supported, it's only meant to be used in the bridge. Also, you shouldn't ping people for no reason.

**Comment by af913337456** [comment]
Thanks to reply, and sorry for that.

The message you mentioned is determined by the phone, but I found that the web version of Google Message can send RCS messages on it, and the web version also calls the same interface as GMessage. GM cannot send, but the web version can. I think the inconsistency here may be due to the lack of some requests.

**Comment by tulir** [comment]
RCS messages work just fine in the bridge as long as RCS is enabled on the phone (and in the case of dual sims, the chat is set to use the SIM with RCS enabled)

**Comment by af913337456** [comment]
@tulir Thanks again! I have more detail about this, below 👇:

This is strange. I am sure I have enabled the RCS function on my phone, and as the recipient of the message, my friend's phone is also enabled. And before that, we had not sent any messages through Google Message, which means we had not established a conversation. Then I sent him an RCS message through Gmessage, and finally checked the interface on my phone. It showed sending SMS instead of RCS, but since I opened a chat session with him on my Google Message as the sender, I was able to send RCS messages through Gmessage. That is to say, the keyword here is that when we use Gmessage to send RCS messages, we have already opened a conversation on Google Message and received a prompt saying, 'You are currently conducting RCS with xxx'

**Comment by af913337456** [comment]
> @tulir Thanks again! I have more detail about this, below 👇:
> 
> This is strange. I am sure I have enabled the RCS function on my phone, and as the recipient of the message, my friend's phone is also enabled. And before that, we had not sent any messages through Google Message, which means we had not established a conversation. Then I sent him an RCS message through Gmessage, and finally checked the interface on my phone. It showed sending SMS instead of RCS, but since I opened a chat session with him on my Google Message as the sender, I was able to send RCS messages through Gmessage. That is to say, the keyword here is that when we use Gmessage to send RCS messages, we have already opened a conversation on Google Message and received a prompt saying, 'You are currently conducting RCS with xxx'

And once i open the conversation with some phone who support the RCS fucntion on the GoogleMessage APP. i can see this event 'TOMBSTONE_PROTOCOL_SWITCH_TO_RCS' on the GMessage server log. After that, all goes find.

```log
Received message conversation_id=2197 is_old=false message_id=3992 message_status=TOMBSTONE_ONE_ON_ONE_RCS_CREATED message_ts=1697631738005000 participant_id=3 tmp_id= user_id=111222
```

**Comment by af913337456** [comment]
@tulir Morning sir, I have a small guess, is it the interface for creating a session, and what parameters can be specified to be an RCS session, but not the RCS-Group one.

**Comment by af913337456** [comment]
Anyone who can solve this problem, contact me, $3000 will pay to you.
