### ISSUE TITLE
Google account pairing doesn't need the 2 second sleep

### ISSUE THREAD

**Issue by outlandishphalanx** [mautrix/gmessages#22]
Referring to this line here:

https://github.com/mautrix/gmessages/blob/4cac56381b6521fd7731af42e5243db0e70209b9/libgm/pair_google.go#L365

At the point the client making the pairing has received the response to the client finish RPC, it is safe to immediately start sending traffic. So, this sleep can simply be removed.

**Comment by tulir** [comment]
Makes sense, will remove that

In case you feel like helping with other things, here's the current list of weird things I haven't been able to figure out fully:

* Google account pairing seems to have caused more issues where the phone stops responding frequently for some users (even with battery optimizations disabled). Switching to QR pairing usually makes it work better for the affected users. Is the bridge doing something wrong or could that be an issue on Google's side?
* Sometimes the phone seems to silently stop sending messages (without sending a `BROWSER_INACTIVE` alert or anything). I'm working around it by sending extra `GET_UPDATES` requests if the bridge doesn't receive any data for over 3 hours or if the phone doesn't respond to pings for some time, but that feels very hacky and isn't fully reliable. Is the phone supposed to do that and is there a proper solution?
* Any chance you know what response codes 2, 3 and 4 mean in send message responses? I'm pretty sure they're failures, but it'd be nice to know what they mean
  https://github.com/mautrix/gmessages/blob/0236ea64b6de686db351560a3f15d6966a5816e9/libgm/gmproto/client.proto#L282-L284
* I've seen some cases where the phone sends a success/status 1 response to a message send request, but then the message just disappears never to be seen again. Should the bridge just retry if it doesn't get an echo of outgoing messages some time after a successful ack?

**Comment by outlandishphalanx** [comment]
I sent a message to your Google Chat account to follow up
