### ISSUE TITLE
Messages sometimes get added to Matrix from GMessages with the wrong timestamp

### ISSUE THREAD

**Issue by wunter8** [mautrix/gmessages#4]
I've had some messages get added to Matrix with the wrong timestamp, so they appear to have been sent/received on the wrong day. Here's an example:

![Screenshot_20230726-131750](https://github.com/mautrix/gmessages/assets/8421688/7f218bc2-24ee-4761-8971-6cdfa50edc9c)
![Screenshot_20230726-130741](https://github.com/mautrix/gmessages/assets/8421688/e9a06a1a-e68e-4fbe-bada-b85d79b2539f)

My message was sent in March as shown in the first image, but it looks like I sent it in July in Matrix

**Comment by tulir** [comment]
You'll need to modify synapse or add yourself to an appservice namespace to get timestamp massaging with double puppeting. https://github.com/matrix-org/synapse/blob/v1.88.0/synapse/rest/client/room.py#L283 is the specific line that needs to be removed (the `if` condition, not the line inside the if, you could replace it with `if True:`). My synapse fork exposes it as a convenient config option (https://mau.dev/maunium/synapse/-/commit/0bc5a9145441d5e5714b4ac6b315e28688cf3ee7)

**Comment by wunter8** [comment]
If I modify synapse and restart synapse and the bridge, will the timestamps update? Or would I need to clear the DB and reconnect the bridge to backfill everything again?

**Comment by tulir** [comment]
Existing events never change
